### ISSUE TITLE
`NoSuchMethodError` When Using `org.scalameta::munit:1.0.0-M7` 

### ISSUE THREAD

**Issue by ASRagab** [typelevel/munit-cats-effect#267]
👋🏽 Hello,

I encountered an issue running `CatsEffectSuite` tests with cats-effect3 and the latest milestone of  `munit` see below for minimum reproduction:

`repro.scala`
```scala
//> using scala "2.13"
//> using lib "org.typelevel::cats-effect:3.4.5"
//> using lib "org.scalameta::munit:1.0.0-M7"
//> using lib "org.typelevel::munit-cats-effect-3:1.0.7"

import cats.effect.IO
import munit.CatsEffectSuite

class Repro extends CatsEffectSuite {
  test("repro") {
    IO(3).assertEquals(3)
  }
}
```

`> scala-cli test .`

Error:
```
==> X Repro.initializationError  0.001s java.lang.NoSuchMethodError: 'void munit.ValueTransforms$ValueTransform.<init>(munit.FunSuite, java.lang.String, scala.PartialFunction)'
    at munit.CatsEffectSuite.<init>(CatsEffectSuite.scala:42)
    at Repro.<init>(files.scala:9)
    at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
    at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
    at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341)
    at java.lang.Class.newInstance(Class.java:677)
    at munit.MUnitRunner$$anonfun$$lessinit$greater$1.apply(MUnitRunner.scala:33)
    at munit.MUnitRunner$$anonfun$$lessinit$greater$1.apply(MUnitRunner.scala:33)
    at munit.MUnitRunner.<init>(MUnitRunner.scala:35)
    at munit.MUnitRunner.<init>(MUnitRunner.scala:33)
    at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
    at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:483)
    at munit.internal.junitinterface.JUnitComputer.getRunner(JUnitComputer.java:75)
    at munit.internal.junitinterface.JUnitComputer$1.runnerForClass(JUnitComputer.java:65)
    ...
```

With `org.scalameta::munit:0.7.29`:

```
Repro:
  + repro 0.041s
```

**Comment by armanbilge** [comment]
Munit `1.0.0-M7` is a breaking change and is not compatible with munit-cats-effect 1.x series.

You can use the 2.x milestone releases. Note the artifact has been renamed to `munit-cats-effect`, no `-3`.
https://github.com/typelevel/munit-cats-effect/releases/tag/v2.0.0-M3

**Comment by ASRagab** [comment]
Oh, sorry, I missed this, apologies, this is resolved. You can close this. Thank you!
