### ISSUE TITLE
Promise exception on 2.12

### ISSUE THREAD

**Issue by cquiroz** [typelevel/munit-cats-effect#60]
In one of my tests I'm using a fixture and I see these messages on the log, surprisingly in 2.12 only and the error itself runs fine it just print these

```
java.lang.IllegalStateException: Promise already completed.
  | => oat scala.concurrent.Promise.complete(Promise.scala:53)
        at scala.concurrent.Promise.complete$(Promise.scala:52)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
        at scala.concurrent.Promise.failure(Promise.scala:104)
        at scala.concurrent.Promise.failure$(Promise.scala:104)
        at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:187)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:45)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at munit.Suite$$anon$1.execute(Suite.scala:26)
```

The error itself is kind of complicated but I could try to produce a minimal reproduction in needed

**Comment by RaasAhsan** [comment]
I just ran into this too, when using `ResourceFixture` and assigning it to a `val`. The constructor for `ResourceFixture` isn't pure -- it creates a `Promise` that holds the resource finalizer once the effect has been run. So if the effect runs multiple times, the same promise is created multiple times.

Quick fix for it was to create a new fixture every time by declaring it a `def`, but `val` should certainly work here too since fixtures are just data

**Comment by RaasAhsan** [comment]
I think the obvious solution here is to make the `ResourceFixture` constructor pure by returning `IO[FunFixture[T]]` and adding syntax to run tests off those. Unfortunately there isn't really another channel to share the finalizer (FunFixture is an invariant functor)

@mpilquist thoughts ?

**Comment by mpilquist** [comment]
Ouch, yeah that's nasty. `SyncIO[FunFixture[T]]` makes sense to me.
